use studentsData;

CREATE TABLE IF NOT EXISTS students(
ID INT AUTO_INCREMENT NOT NULL,
FirstName VARCHAR(255),
LastName VARCHAR(255),
DOB datetime DEFAULT CURRENT_TIMESTAMP,
MAJOR VARCHAR(255),
PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS instructors(
ID INT AUTO_INCREMENT NOT NULL,
FirstName VARCHAR(255),
LastName VARCHAR(255),
DOB Date,
PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS courses(
ID INT AUTO_INCREMENT NOT NULL,
CourseName VARCHAR(255),
InstructorId INT,
FOREIGN KEY (InstructorId) REFERENCES instructors(ID),
PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS transactionals(
ID INT AUTO_INCREMENT NOT NULL,
Course_ID INT,
Student_ID INT,
FOREIGN KEY (Course_ID) REFERENCES courses(ID),
FOREIGN KEY (Student_ID) REFERENCES students(ID),
PRIMARY KEY (ID)
);
